#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sabnzbd"
name = "SABnzbd"
description.en = "The Free and easy binary newsreader for downloading, verifying and extracting files from Usenet"
description.fr = "Le lecteur de news binaire gratuit et simple pour télécharger, vérifier et extraire des fichiers depuis Usenet"

version = "4.5.3~ynh1"

maintainers = ["bowgartfield"]

[upstream]
license = "GPL-2.0"
website = "https://sabnzbd.org"
admindoc = "https://sabnzbd.org/wiki/"
userdoc = "https://sabnzbd.org/wiki/"
code = "https://github.com/sabnzbd/sabnzbd"
cpe = "cpe:2.3:a:sabnzbd:sabnzbd"
fund = "https://sabnzbd.org/donate/"

[integration]
yunohost = ">= 12.1.30"
helpers_version = "2.1"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = false

sso = false

disk = "100M"
ram.build = "100M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sabnzbd"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

        [resources.sources.main]
        # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
        #    ynh_setup_source --dest_dir="$install_dir"
        # You can also define other assets than "main" and add --source_id="foobar" in the previous command
        url = "https://github.com/sabnzbd/sabnzbd/releases/download/4.5.3/SABnzbd-4.5.3-src.tar.gz"
        sha256 = "c745eeb9f66939f9257ad06042b63fac575aea44604bcdf90bbc8a33cd13e4a0"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "complete", "incomplete", "admin" ]

    [resources.permissions]
    main.url = "/"
    main.protected = true
    main.allowed = "admins"

    [resources.ports]

    [resources.apt]
    packages = "python3-venv, python3-dev, python3-pip, python3-setuptools, libffi-dev, libssl-dev, par2, unzip, p7zip-full"
    
    # Additional packages from non-free repository  
    extras.non_free.repo = "deb http://deb.debian.org/debian bookworm non-free"
    extras.non_free.key = ""
    extras.non_free.packages = ["unrar"]