#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # Exclude private and multi-instance tests for now
    exclude = ["install.private", "install.multi"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # Set default language for tests
    args.language = "en"
